version: "3"
services:
  core-customer:
    build:
      context: ../../core-customer
      dockerfile: Dockerfile
    environment:
        - 'APP_ENVIRONMENT=dev'
        - 'DATABASE_HOST=db_core_customer'
        - 'DATABASE_PORT=3306'
        - 'DATABASE_NAME=db_core_customer'
        - 'DATABASE_USERNAME=customer'
        - 'DATABASE_PASSWORD=password'
        - 'KAFKA_HOST=kafka-broker'
        - 'KAFKA_PORT=9092'
        - 'REDIS_HOST_2=cache_redis'
    networks:
      - private

  app-customer:
    build:
      context: ../../app-customer
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - 'APP_ENVIRONMENT=dev'
      - 'DATABASE_HOST=db_app_customer'
      - 'DATABASE_PORT=3306'
      - 'DATABASE_NAME=db_app_customer'
      - 'DATABASE_USERNAME=customer'
      - 'DATABASE_PASSWORD=password'
      - 'KAFKA_HOST=kafka-broker'
      - 'KAFKA_PORT=9092'
      - 'CORE_CUSTOMER_API_HOST=core-customer'
    networks:
      - private

networks:
  private:
    external: true
  public:
    external: true