version: "3"
services:
  core-customer:
    image: 119944160132.dkr.ecr.us-east-2.amazonaws.com/core-customer:1.0.0-release-005
    environment:
      - APP_PORT=8080
      - APP_ENVIRONMENT=prod
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - AWS_REGION=${AWS_REGION}
      - DATABASE_HOST=database-1.c10qi4oq8v59.us-east-2.rds.amazonaws.com
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root12345
      - CONSUL_HOST=consul-discovery
      - CONSUL_PORT=8500
      - REDIS_HOST=redis
    networks:
      - private

networks:
  private:
    external: true
  public:
    external: true