version: "3"
services:
  core-customer:
    image: 119944160132.dkr.ecr.us-east-2.amazonaws.com/core-customer:1.0.0-release-005
    environment:
      - 'APP_PORT=8080'
      - 'APP_ENVIRONMENT=prod'
      - 'AWS_ACCESS_KEY_ID=AKIARX3J2UOCCTR36J4S'
      - 'AWS_ACCOUNT_ID=119944160132'
      - 'AWS_REGION=us-east-2'
      - 'AWS_SECRET_ACCESS_KEY=BhIyeMal6Po3G8/cmbcH+oIpUbIR8AVV3rvxux9u'
      - 'DATABASE_HOST=database-1.c10qi4oq8v59.us-east-2.rds.amazonaws.com'
      - 'DATABASE_PORT=3306'
      - 'DATABASE_USERNAME=root'
      - 'DATABASE_PASSWORD=root12345'
      - 'CONSUL_HOST=consul-discovery'
      - 'CONSUL_PORT=8500'
      - 'REDIS_HOST=redis'
    networks:
      - private

networks:
  private:
    external: true
  public:
    external: true